# Generated by Django 3.2.15 on 2022-08-29 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Users',
            new_name='Users',
        ),
    ]
