# Generated by Django 4.0.7 on 2022-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
