# Generated by Django 3.2.15 on 2022-09-27 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 27), null=True),
        ),
    ]
