# Generated by Django 4.0.7 on 2022-09-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='autochout',
            field=models.BooleanField(default=False),
        ),
    ]
