# Generated by Django 3.2.15 on 2022-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0005_auto_20220915_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
