# Generated by Django 4.0.7 on 2022-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0005_attendance_autochout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='autochout',
        ),
        migrations.AddField(
            model_name='employee',
            name='autochout',
            field=models.BooleanField(default=False),
        ),
    ]
