# Generated by Django 4.0.7 on 2022-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0006_remove_attendance_autochout_employee_autochout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='autochout',
            field=models.IntegerField(default=0),
        ),
    ]
