# Generated by Django 3.2.15 on 2022-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
